version: '3'

tasks:
  build:
    desc: Build the app
    cmds:
      - go build -o bin/project-a main.go

  run-dev:
    desc: Run the app dev mode
    cmds:
      - go run main.go

  run:
    desc: Run the app using binary file
    deps: [build]
    cmds:
      - bin/project-a
