apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-a
  labels:
    app: project-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-a
  template:
    metadata:
      labels:
        app: project-a
    spec:
      containers:
      - name: api
        image: ghcr.io/romsnl/project-a/dev:latest
        ports:
        - containerPort: 3001
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3001
          initialDelaySeconds: 0
          periodSeconds: 10
        resources:
          requests:
            memory: "16Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "100m"
