name: Build

on:
  push:
    branches:
      - main

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: ghcr.io login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        uses: docker/build-push-action@v2
        with:
          file: ${{ env.DOCKERFILE_PATH }}
          context: ./
          push: false
          no-cache: true
          tags: ghcr.io/romsnl/project-a/dev:latest
          labels: org.opencontainers.image.revision=${{ github.sha }}
